name: 'Dev - PR Open'
on:
  pull_request:
    branches:
      - master
    types:
      - opened
jobs:
  add_comment:
    name: 'Add Comment'
    runs-on: ubuntu-latest
    steps:
      - uses: mshick/add-pr-comment@v1
        with:
          message: Please set a versioning label of either `major`, `minor`, or `patch` to the pull request.
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions-ecosystem/action-add-labels@v1
        if: ${{! (contains(github.event.pull_request.labels.*.name, 'patch') || contains(github.event.pull_request.labels.*.name, 'minor') || contains(github.event.pull_request.labels.*.name, 'major'))}}
        with:
          labels: patch