name: Auto-bump-version on merging a Pull Request

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump version
        id: package_version
        uses: KageKirin/bump-node-package-version@v0
        with:
          patch: true

      - name: Commit new version
        run: |
          git commit -am "CI: bump version to ${{ steps.test.package_version.version }}"
          git tag -m "CI: create new tag" v${{ steps.test.package_version.version }}
          # git push --follow-tags https://${{ github.token }}@github.com/OWNER/REPO
          git push origin master --follow-tags