name: Auto-bump-version with yarn

on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Git config
        run: |
          git config user.email "john.doe@gmail.com"
          git config user.name "Lala and Joe"

      - name: Commit new version
        run: |
          yarn version --patch
          git push origin master --follow-tags